export enum Routes {
  HOME='/',
  LOGIN = '/login',
  DEMO_BOOKING = 'https://calendly.com/admin-playervista/demo-book',
  EMAIL_VERIFICATION = '/verify-email/:token',
  TEAM = '/team',
  CREATE_TEAM = '/team/create-team',
  MANAGE_TEAM = '/team/:teamId/manage-teams',
  DASHBOARD_CREATE_TEAM = '/team/:teamId/team/create-team',
  DASHBOARD = '/team/:teamId',
  PLAYERS = '/team/:teamId/players',
  STATISTICS = '/team/:teamId/statistics',
  ADD_PLAYER = '/team/:teamId/players/add-player',
  SINGLE_PLAYER = '/team/:teamId/players/:playerId',
  STAFFS = '/team/:teamId/staffs',
  ADD_STAFF = '/team/:teamId/staffs/add-staff',
  REPORTERS = '/team/:teamId/reporters',
  ADD_REPORTERS = '/team/:teamId/reporters/add-reporter',
  TRAINING_DATA = '/team/:teamId/training-data',
  EVENTS = '/team/:teamId/events',
  SINGLE_EVENT = '/team/:teamId/events/:eventId',
  EVENT_SUMMARY = '/team/:teamId/event/:eventId/stats',
  PLAYER_EVENT_STATS = '/team/:teamId/event/:eventId/stats/:playerId',
  ACCOUNT= '/dashboard/my-account',
  LOGOUT = '/logout',
  SIGN_UP = '/onboard',
  FORGOT_PASSWORD = '/forgot-password',
  CHANGE_PASSWORD = '/change-password'
}

export const routes = {
  home: Routes.HOME,
  login: Routes.LOGIN,
  demoBooking: Routes.DEMO_BOOKING,
  emailVerification: Routes.EMAIL_VERIFICATION,
  team: Routes.TEAM,
  manageTeam: Routes.MANAGE_TEAM,
  dashboardCreateTeam: Routes.DASHBOARD_CREATE_TEAM,
  createTeam: Routes.CREATE_TEAM,
  signUp: Routes.SIGN_UP,
  dashboard: Routes.DASHBOARD,
  players: Routes.PLAYERS,
  statistics: Routes.STATISTICS,
  addPlayer: Routes.ADD_PLAYER,
  reporters: Routes.REPORTERS,
  addReporter: Routes.ADD_REPORTERS,
  singlePlayer: Routes.SINGLE_PLAYER,
  staffs: Routes.STAFFS,
  addStaff: Routes.ADD_STAFF,
  trainingData: Routes.TRAINING_DATA,
  events: Routes.EVENTS,
  singleEvent: Routes.SINGLE_EVENT,
  eventSummary: Routes.EVENT_SUMMARY,
  playerEventStats: Routes.PLAYER_EVENT_STATS,
  account: Routes.ACCOUNT,
  logout: Routes.LOGOUT,
  forgotPassword: Routes.FORGOT_PASSWORD,
  changePassword: Routes.CHANGE_PASSWORD,
}
