import { PdfTypeEnum } from '@/config/PdfType'

/**
 * Helper function to create PDF export options for player season reports
 * @param playerId The ID of the player
 * @param playerName The name of the player for the report title
 * @param teamName Optional team name
 * @returns PDF export options object to pass to ExportPdfButton
 */
export const createPlayerSeasonPdfOptions = (
  playerId: string,
  playerName: string,
  teamName?: string,
) => {
  return {
    title: `${playerName} - Season Performance Report`,
    subtitle: teamName ? `${teamName} - Season Analysis` : 'Season Analysis',
    exportType: PdfTypeEnum.FULL_PLAYER_REPORT,
    playerId: playerId,
    filename: `${playerName.replace(/\s+/g, '-').toLowerCase()}-season-report.pdf`,
    includeImages: true,
    footerText: 'Generated by PlayerVista',
  }
}

/**
 * Helper function to create PDF export options for player match reports
 * @param playerId The ID of the player
 * @param playerName The player's name for the report title
 * @param eventId The ID of the match event
 * @param opponentName Optional opponent name for the title
 * @param matchDate Optional match date for the filename
 * @returns PDF export options object to pass to ExportPdfButton
 */
export const createPlayerMatchPdfOptions = (
  playerId: string,
  playerName: string,
  eventId: string,
  opponentName?: string,
  matchDate?: string,
) => {
  const opponent = opponentName || 'Opponent'
  const dateStr = matchDate ? `-${matchDate.replace(/\//g, '-')}` : ''

  return {
    title: `${playerName} vs ${opponent} - Match Report`,
    subtitle: 'Match Performance Analysis',
    exportType: PdfTypeEnum.SINGLE_MATCH_PLAYER_REPORT,
    playerId: playerId,
    eventId: eventId,
    filename: `${playerName.replace(/\s+/g, '-').toLowerCase()}-vs-${opponent.toLowerCase().replace(/\s+/g, '-')}${dateStr}-match-report.pdf`,
    includeImages: true,
    footerText: 'Generated by PlayerVista',
  }
}
